run:
  modules-download-mode: readonly
  timeout: 15m
  tests: false
issues:
  max-same-issues: 20
linters:
  disable-all: true
  enable:
    - bodyclose
    - staticcheck
    - errcheck
    - typecheck
    - unused
    - depguard
    - unconvert
    - nakedret
    - exportloopref
    - gocritic
    - gosimple
    - ineffassign
    - asciicheck
    - contextcheck
    - dogsled
    - dupl
    - nilerr
    - unparam

linters-settings:
  unparam:
    check-exported: true

  staticcheck:
    go: "1.20"
    checks: ["all"]

  depguard:
    include-go-root: true
    packages-with-error-message:
      - github.com/rs/zerolog: "use logrus"
      - github.com/apex/log: "use logrus"
      - github.com/inconshreveable/log15: "use logrus"
      - go.uber.org/zap: "use logrus"
      - log: "use logrus"

  nakedret:
    max-func-lines: 0

  gosimple:
    go: "1.20"
    checks: ["all"] # https://staticcheck.io/docs/options#checks

  dogsled:
    max-blank-identifiers: 1

  dupl:
    threshold: 100

  # errcheck:
  # exclude-functions:
  # - (net/http.ResponseWriter).Write
