[Service]
ExposeSwagger=true
Port=8080
ReadTimeout=100
WriteTimeout=120
IdleTimeout=100

[Buffer]
LoopTimeout=6
Size=10000

[Database]
DialTimeout=10
MaxOpenConns=5
MaxIdleConns=5
ConnMaxLifetime=3600
Debug=false