[Service]
ExposeSwagger=true
Port=8080
ReadTimeout=100
WriteTimeout=120
IdleTimeout=100

[Buffer]
RetriesLeft=3
LoopTimeout=10
Size=10000

[Database]
TableName="dev"
DialTimeout=10
MaxOpenConns=5
MaxIdleConns=5
ConnMaxLifetime=3600
Debug=false
